# Generated by Django 5.1.7 on 2025-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=75)),
                ('trophy', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
