# Generated by Django 5.1.7 on 2025-04-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="profile_pic",
            new_name="pic",
        ),
    ]
