# Generated by Django 5.1.7 on 2025-04-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
