# Generated by Django 5.1.7 on 2025-04-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="history",
        ),
        migrations.RemoveField(
            model_name="post",
            name="person",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="History",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
