# Generated by Django 5.1.7 on 2025-04-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0007_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="last_analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_analysis_for_person",
                to="data_app.history",
            ),
        ),
    ]
