# Generated by Django 5.1.7 on 2025-04-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0008_person_last_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="person",
        ),
        migrations.RemoveField(
            model_name="post",
            name="history",
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_analysis",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="History",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
