# Generated by Django 5.1.7 on 2025-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0010_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="trophies",
        ),
        migrations.AddField(
            model_name="post",
            name="trophies",
            field=models.JSONField(default=list),
        ),
    ]
