# Generated by Django 5.1.7 on 2025-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0012_remove_post_trophies_history_trophies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="subreddit",
            field=models.JSONField(default=dict),
        ),
    ]
